List<Map<String,dynamic>>current =[
  {
    "name": "wheat",
    "temperature" : "10°C से 25°C",
    "requiredTemp": "25",
    "cloud_condition" : "मध्यम वर्षा (लगभग 50-75 सेमी)",
    "wind" : "सीधे तौर पर आवश्यक नहीं है",
    "wind_direction" : "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity" : "4 से 6",
    "huf" : "4",
    "hus" : "6",
    "cloud" : "3 से 5",
    "heatindex" : "18-25° सेल्सियस",
    "heat" : "25",
    "dewpoint" : "10-15° सेल्सियस",
    "dew":"10",
    "gust" : "20-30 किमी/घंटा",
    "g":"30",
  },
  {
    "name": "soybean",
    "temperature": "20°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 60-100 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "दक्षिण-पश्चिमी या पश्चिमी",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "4 से 6",
    "heatindex": "22-28° सेल्सियस",
    "heat" : "28",
    "dewpoint": "12-18° सेल्सियस",
    "dew":"12",
    "gust": "15-25 किमी/घंटा",
    "g":"25",
  },
  {
    "name": "potato",
    "temperature": "15°C से 20°C",
    "requiredTemp": "20",
    "cloud_condition": "हल्की वर्षा (लगभग 50-75 सेमी)",
    "wind": "हल्की वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं",
    "humidity": "6 से 8",
    "huf" : "6",
    "hus" : "8",
    "cloud": "3 से 5",
    "heatindex": "15-22° सेल्सियस",
    "heat" : "22",
    "dewpoint": "8-12° सेल्सियस",
    "dew":"8",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name":"tomato",
    "temperature": "20°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "मध्यम वर्षा (लगभग 50-100 सेमी)",
    "wind": "हल्की वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 6",
    "heatindex": "22-28° सेल्सियस",
    "heat" : "28",
    "dewpoint": "12-18° सेल्सियस",
    "dew":"12",
    "gust": "15-25 किमी/घंटा",
  "g":"25",
  },
  {
    "name":"guava",
    "temperature": "23°C से 28°C",
    "requiredTemp": "28",
    "cloud_condition": "कम वर्षा (लगभग 100-150 सेमी)",
    "wind": "मध्यम वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं",
    "humidity": "6 से 8",
    "huf" : "6",
    "hus" : "8",
    "cloud": "4 से 6",
    "heatindex": "24-30° सेल्सियस",
    "heat" : "30",
    "dewpoint": "14-20° सेल्सियस",
    "dew":"14",
    "g":"30",
    "gust": "20-30 किमी/घंटा"
  },
  {
    "name":"orange" ,
    "temperature": "15°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "मध्यम वर्षा (लगभग 75-150 सेमी)",
    "wind": "हल्की से मध्यम वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 5",
    "heatindex": "20-28° सेल्सियस",
    "heat" : "28",
    "dewpoint": "10-18° सेल्सियस",
    "dew":"10",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "chilli",
    "temperature": "20°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 50-100 सेमी)",
    "wind": "हल्की वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 6",
    "heatindex": "22-30° सेल्सियस",
    "heat" : "30",
    "dewpoint": "12-18° सेल्सियस",
    "dew":"12",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "papaya",
    "temperature": "25°C से 35°C",
    "requiredTemp": "35",
    "cloud_condition": "हल्की वर्षा (लगभग 100-150 सेमी)",
    "wind": "मध्यम वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "6 से 8",
    "huf" : "6",
    "hus" : "8",
    "cloud": "3 से 6",
    "heatindex": "25-35° सेल्सियस",
    "heat" : "35",
    "dewpoint": "15-22° सेल्सियस",
    "dew":"15",
    "g":"30",
    "gust": "20-30 किमी/घंटा"
  },
  {
    "name": "cotton",
    "temperature": "25°C से 35°C",
    "requiredTemp": "35",
    "cloud_condition": "कम से मध्यम वर्षा (लगभग 50-100 सेमी)",
    "wind": "मध्यम वायु आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 5",
    "heatindex": "25-35° सेल्सियस",
    "heat" : "35",
    "dewpoint": "15-22° सेल्सियस",
    "dew":"15",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "babul (gond)",
    "temperature": "20°C से 40°C",
    "requiredTemp": "40",
    "cloud_condition": "कम वर्षा (लगभग 30-50 सेमी)",
    "wind": "सीधे तौर पर आवश्यक नहीं है",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "3 से 5",
    "huf" : "3",
    "hus" : "5",
    "cloud": "1 से 3",
    "heatindex": "20-38° सेल्सियस",
    "heat" : "38",
    "dewpoint": "10-18° सेल्सियस",
    "dew":"10",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "lady finger",
    "temperature": "20°C से 35°C",
    "requiredTemp": "35",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 50-100 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "2 से 4",
    "heatindex": "22-30° सेल्सियस",
    "heat" : "30",
    "dewpoint": "15-20° सेल्सियस",
    "dew":"15",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "brinjal",
    "temperature": "20°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 50-75 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 5",
    "heatindex": "22-28° सेल्सियस",
    "heat" : "28",
    "dewpoint": "15-20° सेल्सियस",
    "dew":"15",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "cauliflower",
    "temperature": "15°C से 25°C",
    "requiredTemp": "25",
    "cloud_condition": "हल्की वर्षा (लगभग 50-60 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "6 से 8",
    "huf" : "6",
    "hus" : "8",
    "cloud": "3 से 6",
    "heatindex": "18-24° सेल्सियस",
    "heat" : "24",
    "dewpoint": "10-15° सेल्सियस",
    "dew":"10",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "carrot",
    "temperature": "10°C से 20°C",
    "requiredTemp": "20",
    "cloud_condition": "हल्की वर्षा (लगभग 40-50 सेमी)",
    "wind": "मध्यम वायु प्रवाह सहनीय",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "6 से 8",
    "huf" : "6",
    "hus" : "8",
    "cloud": "3 से 5",
    "heatindex": "15-22° सेल्सियस",
    "heat" : "22",
    "dewpoint": "8-12° सेल्सियस",
    "dew":"8",
    "g":"15",
    "gust": "10-15 किमी/घंटा"
  },
  {
    "name": "dhaniya",
    "temperature": "15°C से 25°C",
    "requiredTemp": "25",
    "cloud_condition": "हल्की वर्षा (लगभग 40-50 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "2 से 4",
    "heatindex": "18-24° सेल्सियस",
    "heat" : "24",
    "dewpoint": "10-14° सेल्सियस",
    "dew":"10",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "methi",
    "temperature": "10°C से 25°C",
    "requiredTemp": "25",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 40-60 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "4 से 6",
    "huf" : "4",
    "hus" : "6",
    "cloud": "2 से 4",
    "heatindex": "15-22° सेल्सियस",
    "heat" : "22",
    "dewpoint": "8-12° सेल्सियस",
    "dew":"8",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "shaljam",
    "temperature": "10°C से 20°C",
    "requiredTemp": "20",
    "cloud_condition": "हल्की से मध्यम वर्षा (लगभग 40-60 सेमी)",
    "wind": "मध्यम वायु प्रवाह आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "5 से 7",
    "huf" : "5",
    "hus" : "7",
    "cloud": "3 से 5",
    "heatindex": "12-18° सेल्सियस",
    "heat" : "18",
    "dewpoint": "6-10° सेल्सियस",
    "dew":"6",
    "g":"25",
    "gust": "15-25 किमी/घंटा"
  },
  {
    "name": "banana",
    "temperature": "15°C से 35°C",
    "requiredTemp": "35",
    "cloud_condition": "मध्यम से अधिक वर्षा (लगभग 100-150 सेमी)",
    "wind": "हल्की से मध्यम हवा आवश्यक",
    "wind_direction": "कोई विशिष्ट आदर्श वायु दिशा नहीं है",
    "humidity": "7 से 9",
    "huf" : "7",
    "hus" : "9",
    "cloud": "4 से 6",
    "heatindex": "20-30° सेल्सियस",
    "heat" : "30",
    "dewpoint": "15-20° सेल्सियस",
    "dew":"15",
    "g":"20",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "watermelon",
    "temperature": "22°C से 35°C",
    "requiredTemp": "35",
    "cloud_condition": "कम से मध्यम वर्षा (लगभग 40-60 सेमी)",
    "wind": "हल्की हवा लाभकारी होती है",
    "wind_direction": "कोई विशिष्ट दिशा आवश्यक नहीं",
    "humidity": "6 से 8",
    "huf": "6",
    "hus": "8",
    "cloud": "2 से 4",
    "heatindex": "24-32° सेल्सियस",
    "heat": "32",
    "dewpoint": "12-18° सेल्सियस",
    "dew": "12",
    "g": "15",
    "gust": "10-20 किमी/घंटा"
  },
  {
    "name": "mango",
    "temperature": "24°C से 30°C",
    "requiredTemp": "30",
    "cloud_condition": "मध्यम वर्षा (लगभग 75-100 सेमी)",
    "wind": "हल्की हवा आवश्यक होती है, तेज हवा हानिकारक",
    "wind_direction": "दिशा का विशेष प्रभाव नहीं",
    "humidity": "6 से 8",
    "huf": "6",
    "hus": "8",
    "cloud": "3 से 5",
    "heatindex": "25-32° सेल्सियस",
    "heat": "32",
    "dewpoint": "15-20° सेल्सियस",
    "dew": "15",
    "g": "18",
    "gust": "15-25 किमी/घंटा"
  },
];